version: "3.9"

services:

  backend:
    build: ./backend
    ports:
      - "2000:2000"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    command: npm run dev

  frontend:
    build: ./frontend
    ports:
      - "5174:5174"
    environment:
      VITE_API_URL: http://localhost:2000

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Mintfever28@ihsan
      MYSQL_DATABASE: university_library
    ports:
      - "3307:3306"   # host port 3307 → container 3306
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
